const background_options = [
  "Select Background",
  "Blue",
  "Mint Green",
  "Pink",
  "Red",
  "Violet",
  "Yellow",
];

const fur_options = [
  "Select Fur",
  "Brown",
  "Chocolate",
  "Ginger",
  "Sand",
  "Cream",
  "Charcoal",
  "Periwinkle",
  "Panda",
  "Devil",
  "Rose",
  "Zombie",
  "Alien",
  "Skeleton",
  "Glass",
];

const clothes_options = [
  "Santa Suit",
  "Hoodie - Black",
  "Hoodie - White",
  "Hoodie - Blue",
  "Hoodie - Mint",
  "Hoodie - Orange",
  "T-shirt - Black",
  "T-shirt - White",
  "T-shirt - Blue",
  "T-shirt - Mint",
  "T-shirt - Orange",
  "T-shirt - Fast food",
  "Tanktop",
  "Plaid shirt - Black",
  "Plaid shirt - White",
  "Plaid shirt - Blue",
  "Plaid shirt - Red",
  "Plaid shirt - Green",
  "Suit - Black",
  "Suit - White",
  "Suit - Blue",
  "Suit - Tan",
  "Safety vest",
  "Military vest",
  "Safari shirt",
  "Pirate shirt",
  "Wizard robe",
  "SSJ gi",
  "Space suit - White",
  "Space suit - Orange",
];

const mouth_options = ["Select Mouth", "Face mask", "Beard"];

const eyes_options = [
  "Select Eyes",
  "Black shades",
  "Gold shades",
  "Diamond shades",
  "Pirate eye-patch",
];

const head_options = [
  "Santa hat 1",
  "Santa hat 2",
  "Cap - Black",
  "Cap - Grey",
  "Cap - Blue",
  "Cap - Fast food",
  "Beanie - Black",
  "Beanie - Grey",
  "Beanie - Blue",
  "Fedora - Black",
  "Fedora - Blue",
  "Fedora - Tan",
  "Strawhat",
  "Cowboy hat",
  "Top hat",
  "Gatsby hat",
  "Party hat",
  "Crown",
  "Tiara",
  "Antlers",
  "Devil horns",
  "Halo",
  "Angel wings",
  "Backwards cap",
  "Headband - Pink",
  "Headband - Blue",
  "Headband - White",
  "Headband - Black",
  "Headband - Red",
  "Flower crown",
  "Dragon horns",
  "Unicorn horn",
  "Bunny ears",
  "Frog hat",
  "Strawberry hat",
  "Pineapple hat",
  "Watermelon hat",
  "Pizza hat",
  "Hamburger hat",
  "French fries hat",
  "Ice cream hat",
  "Popcorn hat",
  "Fried chicken hat",
];

export const options = {
  background: background_options,
  fur: fur_options,
  clothes: clothes_options,
  mouth: mouth_options,
  eyes: eyes_options,
  head: head_options,
};
